spring.application.name=cinemahub
server.port=5000

spring.data.mongodb.uri=mongodb://127.0.0.1:27017/cinemahub


# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=huytaidz2005@gmail.com
spring.mail.password=mlsfiaittionbfic
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
